name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  run-app:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run Hello World script
      run: node app.js
